# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      types: [py]
      hooks:
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: mixed-line-ending

#    - repo: https://github.com/psf/black
#      rev: stable
#      types: [ python ]
#      hooks:
#        - id: black
#          args: [ --safe ]

    - repo: https://github.com/PyCQA/flake8
      rev: 7.0.0
      hooks:
          - id: flake8
            args: [--config, setup.cfg]

    # Remove output from jupyter notebooks
    - repo: https://github.com/kynan/nbstripout
      rev: 0.7.1
      hooks:
          - id: nbstripout
