# This workflow will install Python dependencies and try to compile the Fortran source code (Linux)

name: Build

on:
  push:
    branches: [master, dev]
  pull_request:
    types: [opened]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build Fortran source code
      run: |
        make
