# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run all tests (master)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.7", "3.10"]  # check oldest and latest supported version
        other-os: [false]

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.other-os }}  # don't cancel due to OS specific failures
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build Fortran source code
      run: |
        make
    - name: Run all tests
      run: |
        pytest
